### ISSUE TITLE
Configuration to Windows

### ISSUE THREAD

**Issue by scriptzeiro** [ChristianChiarulli/nvim#60]
How i ido that's configuration working on Windows

**Comment by ChristianChiarulli** [comment]
I don't use Windows so I have no idea how to support it.

**Comment by haininhhoang94** [comment]
I have some ideas and some configuration for a Windows/WSL support:
- Using Windows Terminal as a GUI option for Neovim
- Using Python.exe in Windows as a Python Intepreter
etc etc

At first I thought I will commit some of the code into @ChristianChiarulli repo for contributing this wonderful project, but since the Windows support might be slight off the Project insight (not related much on improving the Neovim IDE, but to create some function for Windows), do you mind if I create another repo with References from this repo?

**Comment by scriptzeiro** [comment]
Using WSL2 is possible using the repository, the compatibility not is 100%, but is good.  some characters not showing, but not disturb the working

**Comment by irishgreencitrus** [comment]
I've managed to port the config to windows and it can be found [here](https://github.com/irishgreencitrus/SolarVim#install-in-one-command)
